name: Pack & Publish BuildingBlocks to NuGet

on:
  push:
    branches: [main]
    tags:
      - 'v*' # e.g., v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Restore
      run: dotnet restore Pokok.BuildingBlocks.sln

    - name: Build
      run: dotnet build Pokok.BuildingBlocks.sln --configuration Release --no-restore

    - name: Determine Package Version
      id: version
      run: |
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            echo "PACKAGE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          else
            DATE=$(date +%Y%m%d)
            echo "PACKAGE_VERSION=0.1.0-main-${DATE}" >> $GITHUB_ENV
          fi

    - name: Pack with tag version
      run: |
        for proj in $(find src -name '*.csproj'); do
          dotnet pack "$proj" \
            --configuration Release \
            --no-build \
            --output ./nupkgs \
            /p:Version=${{ env.PACKAGE_VERSION }}
        done

    - name: Push packages to NuGet
      if: startsWith(github.ref, 'refs/tags/v')  # Only publish release versions
      run: |
        for pkg in ./nupkgs/*.nupkg; do
          dotnet nuget push "$pkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        done

    - name: Generate Changelog
      id: changelog
      uses: mikepenz/release-changelog-builder-action@v4
      with:
        configuration: ""
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: ${{ steps.changelog.outputs.changelog }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}